### ISSUE TITLE
Exception in ASGI application

### ISSUE THREAD

**Issue by urkl** [FPurchess/preview-service#2]
`
INFO:     10.10.241.1:57548 - "POST /preview/100x100 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 178, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "./app.py", line 60, in preview_endpoint
    file_path = await _store_uploaded_file(file)
  File "./app.py", line 36, in _store_uploaded_file
    contents = await file.read()
AttributeError: 'str' object has no attribute 'read'
`

**Comment by gistrec** [comment]
Same problem :cactus:

**Comment by vb-mesilat** [comment]
+1
Building from Dockerfile makes no difference

**Comment by vb-mesilat** [comment]
Just in case anyone is interested -- there is a similar project https://github.com/jbl2024/preview-generator-docker
It works as expected

**Comment by razinj** [comment]
To fix this you need to build the image yourself and modify the Dockerfile.

Use `USER root` at top of the file.
Add this line : `RUN mkdir -p /tmp/cache && chmod 777 -R /tmp/cache && mkdir -p /tmp/files && chmod 777 -R /tmp/files`

Then build.
Hope this helps.

**Comment by FPurchess** [comment]
@urkl The stacktrace you posted show that you passed a "string" as the POST-parameter instead of an uploaded file. You either missed uploading it as a `multipart/form-data` or forgot to add an `@` in your curl. Closing this issue.

**Comment by FPurchess** [comment]
@razinj please note that all tmp-directories are being created within the `docker-entrypoint.sh`. Your problem is most likely related to the chmod of the mounted volumes.
